name: CI on Push and Pull Request

on:
  pull_request:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Fix the not-a-git-repository issue
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Go fmt
        run: test -z "$(go fmt ${PACKAGES} | tee /dev/stderr)"

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Build
        run: ./scripts/build

      - name: Test
        run: ./scripts/test
